### PR TITLE
massive overhaul to support full RTM/Web APIs

### PR DESCRIPTION
**Pull request by travisghansen**
This uses the latest upstream client.  It now:
 * fully supports the whole of `Web` and `RTM` APIs
 * gracefully reconnects
 * shows node statuses
 * moves API key to `credentials`
 * sends `slackState` with all outbound messages (includes full list of channels, members, team details, etc)
 * automatically updates `slackState` behind the scenes every 10 minutes (should make it configurable)
 * fully documented in `README.md` and usage in the palette

#### TODO
 * ~~update version number~~
 * ~~revamp documentation~~

### CODE REVIEW

**Comment by yayadrian** [comment]
@travisghansen thanks for this massive refactor. I'm just giving it a test in my system but am happy with the code.

**Comment by travisghansen** [comment]
@yayadrian very cool.  I have some minor tweaks yet to commit and of course documentation when we like the interface.

**Comment by travisghansen** [comment]
I've read some of the core `Node-RED` code and based off of that I need to re-architect some items.  I'll rework and get it committed as quickly as possible.

**Comment by travisghansen** [comment]
@yayadrian ok, I think it's in a pretty good state now.

**Comment by travisghansen** [comment]
A couple other considerations:
1. Store `state` values for channels/members/bots/etc as hash map instead of array.  Using the object's `.id` as the key.  This would simplify lookups and make updates to the state easier (wouldn't have to traverse the list to update the item, just update the item at the appropriate key and move on).
1. Internally monitor presence subscriptions (only if the user has subscribed) and save current presence value in the `state` object as well.  Again, probably in a hash map style mentioned above to make lookups easier.

Thoughts?

**Comment by janvda** [comment]
Splendid job of @travisghansen , before integrating I think the 2 TODOs should also be handled:

TODO
update version number
revamp documentation

**Comment by travisghansen** [comment]
@yayadrian I'm no lawyer.  Do I need to add my name to the `LICENSE` file or anything else of that nature?

**Comment by yayadrian** [comment]
@travisghansen Sadly I'm also no lawyer so not really sure on the rules. 
I think it would be nice to add your name, it's so much more your hard work now. 
Make it happen! 👍

**Comment by travisghansen** [comment]
@yayadrian I just noticed the project `LICENSE` is `MIT`.  It's also flagged as `MIT` in `package.json`, however you have the `Apache` license at the top of the `.html` file.  What would you like to do about that?  Remove it from the `.html` file altogether?

**Comment by travisghansen** [comment]
@yayadrian I think this is pretty well code complete.  Just need to know what you'd like me to do with the license at the top of the `.html` file..

**Comment by yayadrian** [comment]
Hey!
Sorry just had a baby so haven't had a chance to check in.
Please remove from the html.
Totally amazed by your work! Thanks so much

**Comment by travisghansen** [comment]
@yayadrian oh wow, congrats!  That's way more important than any of this :)

`js` is a **really really really** side language for me (only really programmed in it for a couple months a little over a year go) so I've probably got something really stupid going on, hopefully it's good enough to solve the current issues without introducing a bunch of new ones.

I also noticed there was a license at the top of the `.js` file, it's removed now as well.  Presuming documentation is locked in I feel this is pretty well 'done'.  I'll commit the npm `lock` file too.

**Comment by travisghansen** [comment]
The only remaining thing I can think of is documenting the process of getting a token (not sure how well it will work with a `user` token.  Everything is committed at this point and I consider code/doc complete.

**Comment by janvda** [comment]
@travisghansen excellent job.  The old issue with slack node not automatically reconnecting didn't appear again since I installed the new version !! Thanks a lot. Jan.

**Pull request merged**
